version: '2'

volumes:
  shared: {}

services:
  producer:
    image: busybox
    volumes:
      - shared:/out
    command: sh -c "while true; do date; sleep 1; done > /out/dates"

  consumer:
    image: ubuntu:14.04
    depends_on:
      - producer
    volumes:
      - shared:/data
    command: tail -f /data/dates

