version: '2'

services:

  app:
    image: ciao

  proxy:
    image: woollyams/nginx-reverse-proxy:201603101638
    depends_on:
      - app
    ports:
      - 5678:80
    environment:
      BACKEND_HOST: app
